repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - build
          - chore
          - ci
          - data
          - docs
          - feat
          - fix
          - refactor
          - revert
          - scores
          - style
          - test
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or:
          - markdown
          - json
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
        exclude: poetry.lock
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/python-poetry/poetry
    rev: "2.0.0"
    hooks:
      - id: poetry-check
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
  - repo: https://github.com/seddonym/import-linter
    rev: v2.0
    hooks:
      - id: import-linter